set_tcp_nodelay true

listener 8884
allow_anonymous true
max_queued_messages 0

# TLS server configuration
certfile /mosquitto/tls/server/server.crt
keyfile /mosquitto/tls/server/server.key

# Client authentication
require_certificate true
cafile /mosquitto/tls/ca/ca.crt
use_identity_as_username true
