set_tcp_nodelay true

listener 10443
protocol websockets
allow_anonymous true
max_queued_messages 0

# TLS server configuration
certfile /mosquitto/tls/server/server.crt
keyfile /mosquitto/tls/server/server.key

# Client authentication (optional - disable for dev)
require_certificate false
