services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt5
    expose:
      - 8884
    ports:
      - 8884:8884
    restart: no
    volumes:
      - ./mosquitto/config:/mosquitto/config:ro
      - ../../var/tls:/mosquitto/tls:ro
