services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt4
    expose:
      - 8883
    ports:
      - 8883:8883
    restart: no
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ../../var/tls:/mosquitto/tls:ro
